# @name createSaleWithCredit
# Create a new sale with credit amount
# With credit amount = 0.99 this transaction will fail and do a rollback, change it and it will be successful
POST http://localhost:8080/ms-sales/api/sales?productId=1&quantity=1&creditAmount=0.99

###

# @name createSaleWithoutCredit
# Create a new sale without credit amount
# By default this transaction is successful
POST http://localhost:8080/ms-sales/api/sales?productId=1&quantity=1

###

# @name createSaleWithHighQuantity
# Create a new sale with high quantity
# This transaction will fail due to insufficient stock
POST http://localhost:8080/ms-sales/api/sales?productId=1&quantity=1000